# Generated by Django 5.0.7 on 2024-07-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRUDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=1000)),
                ('Color', models.CharField(max_length=1000)),
                ('Category', models.CharField(max_length=1000)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
